on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * 1"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Install dependencies
        run: |
          remotes::install_github("richelbilderbeek/bianchi_et_al_2017")
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
        shell: Rscript {0}

      - name: Make
        run: make

